# Generated by Django 5.1.6 on 2025-10-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Glamkart', '0004_galleryimage_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='gallery/videos/')),
            ],
        ),
    ]
