# Generated by Django 5.1.6 on 2025-10-27 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Glamkart', '0005_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
